name = "mew3-api"
main = "src/index.js"
compatibility_date = "2026-03-10"

[vars]
ALLOWED_ORIGINS = "https://mew3.online,https://www.mew3.online,https://xavierguillemot.github.io"

[[d1_databases]]
binding = "DB"
database_name = "mew3-db"
database_id = "8f1e18a9-e328-40b9-8925-bf708c9c12cc"
migrations_dir = "migrations"
